# Mon 19:14:27 05-Nov-2018
begin	identify mercury_dcc_flat.ms - Ap 1
	id	mercury_dcc_flat.ms
	task	identify
	image	mercury_dcc_flat.ms - Ap 1
	aperture	1
	aplow	-0.92
	aphigh	71.07
	units	Angstroms
	features	2
	         29.65     4358.3     4358.3   4.0 1 1 
	        634.31    4916.04    4916.04   4.0 1 1 
	function spline3
	order 1
	sample *
	naverage 1
	niterate 0
	low_reject 3.
	high_reject 3.
	grow 0.
	coefficients	6
		2.
		2.
		1.
		765.
		4684.234804613626
		352.3584356641524

